variables:
  BACKEND_IMAGE: abeygihan/fringe-backend
  FRONTEND_IMAGE: abeygihan/fringe-frontend
  IMAGE_TAG: latest

stages:
  - build
  - deploy

build_backend:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  cache:
    paths: []
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $BACKEND_IMAGE:$IMAGE_TAG fringe-backend
    - docker push $BACKEND_IMAGE:$IMAGE_TAG
    

build_frontend:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $FRONTEND_IMAGE:$IMAGE_TAG React/fringe-client
    - docker push $FRONTEND_IMAGE:$IMAGE_TAG
    
deploy:
  stage: deploy
  before_script:
    - chmod 600 "$SSH_PRIVATE_KEY"
  script:
    - >
      ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" "$SSH_USER@$SSH_HOST" "
        echo '$REGISTRY_PASS' | sudo docker login -u '$REGISTRY_USER' --password-stdin

        
        sudo docker network inspect fringe-net >/dev/null 2>&1 || \
          sudo docker network create fringe-net

        
        sudo docker stop fringe-backend || true
        sudo docker stop fringe-frontend || true
        sudo docker rm fringe-backend || true
        sudo docker rm fringe-frontend || true

        
        sudo docker pull $BACKEND_IMAGE:$IMAGE_TAG
        sudo docker pull $FRONTEND_IMAGE:$IMAGE_TAG

      
        sudo docker run -d --restart always --name fringe-backend \
          --network fringe-net -p 5001:5001 \
          -e MONGO_URL='$MONGO_URL' \
          -e SECRET_KEY='$SECRET_KEY' \
          $BACKEND_IMAGE:$IMAGE_TAG

    
        sudo docker run -d --restart always --name fringe-frontend \
          --network fringe-net -p 3000:80 \
          $FRONTEND_IMAGE:$IMAGE_TAG
      "
